---
- name: Add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
      - ../vars

- name: Warn if OS is unsupported
  fail: msg="OS {{ ansible_distribution }} {{ ansible_distribution_major_version }} is unsupported"
  when: not common.supported_os

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: debian.yml
  when: ansible_os_family == "Debian"

# Common again
- name: Configure ntp file
  template: src=ntp.conf.j2 dest={{ common.ntp_config }}
  tags: ntp
  notify: restart ntp

- name: Start  service
  service: name={{ item }} state=started enabled=true
  with_items: common.services